# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huati', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('coustmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoucang',
            name='hua',
            field=models.ManyToManyField(to='huati.Hua'),
        ),
        migrations.AddField(
            model_name='shoucang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guanzhu',
            name='guanzhu',
            field=models.ManyToManyField(to='huati.Hua'),
        ),
        migrations.AddField(
            model_name='guanzhu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caogao',
            name='neirong',
            field=models.ManyToManyField(to='huati.Hua'),
        ),
        migrations.AddField(
            model_name='caogao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='zuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
