# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0004_auto_20171109_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='faml',
            field=models.CharField(choices=[('女', '女'), ('男', '男')], default='男', max_length=4),
        ),
    ]
