# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0005_auto_20171109_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zuser',
            name='faml',
        ),
    ]
