# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0007_auto_20171110_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guanzhu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shoucang',
            options={},
        ),
    ]
