# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0006_auto_20171110_1103'),
        ('coustmer', '0008_auto_20171110_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoucang',
            name='hua',
        ),
        migrations.RemoveField(
            model_name='shoucang',
            name='user',
        ),
        migrations.AddField(
            model_name='shoucang',
            name='shoucanghua',
            field=models.ManyToManyField(related_name='shoucanghua', to='huati.Hua'),
        ),
        migrations.AddField(
            model_name='shoucang',
            name='shoucanguser',
            field=models.ForeignKey(default=1510303291.133636, on_delete=django.db.models.deletion.CASCADE, related_name='shoucanguser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guanzhu',
            name='guanzhu',
            field=models.ManyToManyField(related_name='guanzhuhuati', to='huati.Hua'),
        ),
        migrations.AlterField(
            model_name='guanzhu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guanzhuuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
