# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0010_auto_20171110_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoucang',
            name='shoucanghua',
            field=models.ManyToManyField(related_name='shoucanghua', to='huati.Hua'),
        ),
    ]
