# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0013_auto_20171111_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanzhu',
            name='guanzhu',
            field=models.ManyToManyField(related_name='guanzhuhuati', to='huati.Huafen'),
        ),
    ]
