# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0014_auto_20171112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoucang',
            name='shoucanghua',
            field=models.ManyToManyField(blank=True, null=True, related_name='shoucanghua', to='huati.Hua'),
        ),
    ]
