# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0015_auto_20171112_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
