# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0004_auto_20171110_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hua',
            name='leibie',
            field=models.CharField(choices=[(0, '文章'), (1, '话题'), (2, '提问')], default=1, max_length=4),
        ),
    ]
