# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0006_auto_20171110_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hua',
            name='yaoqing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邀请人'),
        ),
    ]
