# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0010_auto_20171111_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hua',
            name='fenlei',
            field=models.ManyToManyField(related_name='fenlei', to='huati.Huafen'),
        ),
    ]
