# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0013_auto_20171112_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hua',
            name='fenlei',
            field=models.ManyToManyField(blank=True, null=True, related_name='fenlei', to='huati.Huafen'),
        ),
    ]
