# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huati', '0014_auto_20171112_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hua',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
