# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20171111_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookfenlei',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
