# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentxin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('dianzan', models.IntegerField(default=0, verbose_name='点赞')),
                ('status', models.BooleanField(default=False, verbose_name='是否冻结')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinwen.Commentxin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('desc', models.CharField(max_length=50, verbose_name='新闻描述')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('fenlei', models.CharField(choices=[(0, '时政'), (1, 'IT'), (2, '国际'), (3, '未分类')], default=0, max_length=4)),
                ('status', models.BooleanField(default=False, verbose_name='是否冻结')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-date_publish'],
            },
        ),
    ]
